using BannerKings.Managers.Policies;
using System.Linq;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.SaveSystem;
using static BannerKings.Managers.Policies.BKGarrisonPolicy;
using static BannerKings.Managers.Policies.BKMilitiaPolicy;
using static BannerKings.Managers.Policies.BKCriminalPolicy;

namespace BannerKings.Managers
{
    public class PolicyManager
    {
        [SaveableProperty(100)]
        public Dictionary<Settlement, List<DecisionsElement>> DECISIONS { get; set; }
        private Dictionary<Settlement, HashSet<BannerKingsPolicy>> SettlementPolicies { get; set; }

        public PolicyManager(Dictionary<Settlement, List<DecisionsElement>> DECISIONS, Dictionary<Settlement, HashSet<BannerKingsPolicy>> POLICIES)
        {
            this.DECISIONS = DECISIONS;
            this.SettlementPolicies = POLICIES;
        }

        public bool IsSettlementPoliciesSet(Settlement settlement) => DECISIONS.ContainsKey(settlement);
        public List<DecisionsElement> GetDefaultDecisions(Settlement settlement)
        {
            if (!DECISIONS.ContainsKey(settlement))
                InitializeSettlementPolicies(settlement);

            return DECISIONS[settlement];
        }

        public static void InitializeSettlementPolicies(Settlement settlement)
        {
            if (!BannerKingsConfig.Instance.PolicyManager.DECISIONS.ContainsKey(settlement))
            {
                List<DecisionsElement> decisions = new List<DecisionsElement>();
                if (settlement.IsTown)
                {
                    decisions.Add(new DecisionsElement("Allow slaves to be exported", "Slave caravans will be formed when slave population is big", true, PolicyType.EXPORT_SLAVES));
                    decisions.Add(new DecisionsElement("Accelerate population growth", "Use your influence to provide better housing and allow more population growth", false, PolicyType.POP_GROWTH));
                    decisions.Add(new DecisionsElement("Allow settlement to self-invest", "Income generated by the settlement will be reverted back into it's economic development", false, PolicyType.SELF_INVEST));
                    decisions.Add(new DecisionsElement("Conscript the lowmen", "Extensive recruitment will draft serfs into the militia, costing gold and reducing the productive workforce", false, PolicyType.CONSCRIPTION));
                    decisions.Add(new DecisionsElement("Subsidize the militia", "Improve militia quality by subsidizing their equipment and trainning", false, PolicyType.SUBSIDIZE_MILITIA));
                    decisions.Add(new DecisionsElement("Exempt nobles from taxes", "Exempt nobles from taxes, making them vouch in your favor", false, PolicyType.EXEMPTION));
                }
                else if (settlement.IsVillage)
                {
                    decisions.Add(new DecisionsElement("Accelerate population growth", "Population will grow faster at the cost of influence", false, PolicyType.POP_GROWTH));
                    decisions.Add(new DecisionsElement("Allow settlement to self-invest", "Income generated by the settlement will be reverted back into it's growth", false, PolicyType.SELF_INVEST));
                    decisions.Add(new DecisionsElement("Subsidize the militia", "Improve militia quality by subsidizing their equipment and trainning", false, PolicyType.SUBSIDIZE_MILITIA));
                }
                else
                {
                    decisions.Add(new DecisionsElement("Allow slaves to be exported", "Slave caravans will be formed when slave population is big", true, PolicyType.EXPORT_SLAVES));
                    decisions.Add(new DecisionsElement("Accelerate population growth", "Use your influence to provide better housing and allow more population growth", false, PolicyType.POP_GROWTH));
                    decisions.Add(new DecisionsElement("Allow settlement to self-invest", "Income generated by the settlement will be reverted back into it's economic development", false, PolicyType.SELF_INVEST));
                    decisions.Add(new DecisionsElement("Conscript the lowmen", "Extensive recruitment will draft serfs into the militia, costing gold and reducing the productive workforce", false, PolicyType.CONSCRIPTION));
                    decisions.Add(new DecisionsElement("Subsidize the militia", "Improve militia quality by subsidizing their equipment and trainning", false, PolicyType.SUBSIDIZE_MILITIA));
                    decisions.Add(new DecisionsElement("Exempt nobles from taxes", "Exempt nobles from taxes, making them vouch in your favor", false, PolicyType.EXEMPTION));
                }

                BannerKingsConfig.Instance.PolicyManager.DECISIONS.Add(settlement, decisions);
            }  
        }

        public bool IsPolicyEnacted(Settlement settlement, string policyType, int value)
        {
            BannerKingsPolicy policy = this.GetPolicy(settlement, policyType);
            return policy.selected == value;
        }

        public BannerKingsPolicy GetPolicy(Settlement settlement, string policyType)
        {
            BannerKingsPolicy result = null;
            if (SettlementPolicies.ContainsKey(settlement))
            {
                HashSet<BannerKingsPolicy> policies = SettlementPolicies[settlement];
                BannerKingsPolicy policy = policies.FirstOrDefault(x => x.Identifier == policyType);
                if (policy != null) result = policy;
            } else
            {
                result = GeneratePolicy(settlement, policyType);
                HashSet<BannerKingsPolicy> set = new HashSet<BannerKingsPolicy>();
                set.Add(result);
                SettlementPolicies.Add(settlement, set);
            }

            if (result == null) result = GeneratePolicy(settlement, policyType);

            return result;
        }

        public BannerKingsPolicy GeneratePolicy(Settlement settlement, string policyType)
        {
            if (policyType == "garrison")
                return new BKGarrisonPolicy(GarrisonPolicy.Standard, settlement);
            else if (policyType == "militia")
                return new BKMilitiaPolicy(MilitiaPolicy.Balanced, settlement);
            if (policyType == "tax")
                return new BKTaxPolicy(BKTaxPolicy.TaxType.Standard, settlement);
            else if (policyType == "tariff")
                return new BKTariffPolicy(BKTariffPolicy.TariffType.Standard, settlement);
            if (policyType == "workforce")
                return new BKWorkforcePolicy(BKWorkforcePolicy.WorkforcePolicy.None, settlement);
            else if (policyType == "draft")
                return new BKDraftPolicy(BKDraftPolicy.DraftPolicy.Standard, settlement);
            else return new BKCriminalPolicy(CriminalPolicy.Enslavement, settlement);
        }

        private void AddSettlementPolicy(Settlement settlement)
        {
            SettlementPolicies.Add(settlement, new HashSet<BannerKingsPolicy>());
        }

        public void UpdateSettlementPolicy(Settlement settlement, BannerKingsPolicy policy)
        {
            if (SettlementPolicies.ContainsKey(settlement))
            {
                HashSet<BannerKingsPolicy> policies = SettlementPolicies[settlement];
                BannerKingsPolicy target = policies.FirstOrDefault(x => x.Identifier == policy.Identifier);
                if (target != null) policies.Remove(target);
                policies.Add(policy);
            }
            else
            {
                AddSettlementPolicy(settlement);
            }
        }


        private DecisionsElement GetPolicyElementFromType(PolicyType type)
        {
            if (type == PolicyType.EXPORT_SLAVES)
                return new DecisionsElement("Allow slaves to be exported", "Slave caravans will be formed when slave population is big", true, PolicyType.EXPORT_SLAVES);
            else if (type == PolicyType.POP_GROWTH)
                return new DecisionsElement("Accelerate population growth", "Population will grow faster at the cost of influence", false, PolicyType.POP_GROWTH);
            else return null;
        }

        public bool IsDecisionEnacted(Settlement settlement, PolicyType policy)
        {
            DecisionsElement element = null;
            if (DECISIONS.ContainsKey(settlement))
                element = DECISIONS[settlement].Find(x => x.type == policy);
            return element != null ? element.isChecked : false;
        }

        public void UpdatePolicy(Settlement settlement, PolicyType policy, bool value)
        {
            DecisionsElement element = DECISIONS[settlement].Find(x => x.type == policy);
            if (element != null) element.isChecked = value;  
            else
            {
                DecisionsElement elementToAdd = GetPolicyElementFromType(policy);
                if (elementToAdd != null)
                {
                    elementToAdd.isChecked = value;
                    DECISIONS[settlement].Add(elementToAdd);
                }
            }
        }

        public class DecisionsElement
        {
            [SaveableProperty(1)]
            public string description { get; set; }

            [SaveableProperty(2)]
            public string hint { get; set; }

            [SaveableProperty(3)]
            public bool isChecked { get; set; }

            [SaveableProperty(4)]
            public PolicyType type { get; set; }

            public DecisionsElement(string description, string hint, bool isChecked, PolicyType type)
            {
                this.description = description;
                this.hint = hint;
                this.isChecked = isChecked;
                this.type = type;
            }
        }

        public enum PolicyType
        {
            EXPORT_SLAVES,
            POP_GROWTH,
            SELF_INVEST,
            CONSCRIPTION,
            EXEMPTION,
            SUBSIDIZE_MILITIA
        }
    }
}
